import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API=(import.meta.env.VITE_API_URL||'http://localhost:8000').replace(/\/$/,'');
const starter=['Java','Spring Boot','SQL','REST API','Git','React'];
const locations=['Hyderabad','Bengaluru','Chennai','Visakhapatnam','Pune','Vijayawada','Mumbai','Remote'];

function App(){
 const [skills,setSkills]=useState(starter),[skillInput,setSkillInput]=useState('');
 const [location,setLocation]=useState('Hyderabad'),[freeOnly,setFreeOnly]=useState(false);
 const [data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [active,setActive]=useState('dashboard'),[resume,setResume]=useState(null),[resumeMode,setResumeMode]=useState(false);
 const add=()=>{const s=skillInput.trim();if(s&&!skills.some(x=>x.toLowerCase()===s.toLowerCase()))setSkills([...skills,s]);setSkillInput('')};
 const remove=s=>setSkills(skills.filter(x=>x!==s));
 const analyze=async()=>{setLoading(true);setError('');try{let response;if(resumeMode&&resume){const f=new FormData();f.append('file',resume);f.append('location',location);f.append('interests','Backend Development, Software Engineering');f.append('free_only',freeOnly);response=await fetch(API+'/api/analyze-resume',{method:'POST',body:f});}else{response=await fetch(API+'/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:{name:'Candidate',education:'B.Tech CSE',location,interests:['Backend Development','Software Engineering'],skills},free_only:freeOnly})})}if(!response.ok)throw new Error(await response.text());setData(await response.json());setActive('dashboard')}catch(e){setError(e.message?.slice(0,220)||'Unable to connect to SkillPath AI.')}finally{setLoading(false)}};
 return <div className="app"><Sidebar active={active} setActive={setActive} hasData={!!data}/><main className="main">
   <Topbar data={data}/>
   {!data?<Onboarding skills={skills} setSkills={setSkills} skillInput={skillInput} setSkillInput={setSkillInput} add={add} remove={remove} location={location} setLocation={setLocation} locations={locations} freeOnly={freeOnly} setFreeOnly={setFreeOnly} resume={resume} setResume={setResume} resumeMode={resumeMode} setResumeMode={setResumeMode} analyze={analyze} loading={loading} error={error}/>:<Results data={data} active={active} setActive={setActive} profile={data.profile} freeOnly={freeOnly}/>} 
 </main></div>
}

function Sidebar({active,setActive,hasData}){return <aside className="sidebar"><div className="brand"><div className="brandMark">S</div><div><b>SkillPath</b><span>AI CAREER AGENT</span></div></div><div className="navLabel">WORKSPACE</div>{[['dashboard','⌂','Overview'],['jobs','◎','Job matches'],['roadmap','↗','My roadmap']].map(([id,icon,label])=><button key={id} disabled={!hasData&&id!=='dashboard'} className={`nav ${active===id?'active':''}`} onClick={()=>setActive(id)}><i>{icon}</i>{label}</button>)}<div className="sidebarBottom"><div className="pipeline"><div className="liveDot"/><div><b>Agent pipeline</b><span>RAG · FAISS · LangGraph</span></div></div><div className="version">C4 • DEMO BUILD</div></div></aside>}
function Topbar({data}){return <header className="topbar"><div><div className="eyebrow">C4 / SKILL-GAP-TO-JOB MATCHING</div><h1>{data?'Your path to the next opportunity.':'Turn skills into opportunities.'}</h1></div><div className="headerPill"><span/>RAG ONLINE</div></header>}

function Onboarding({skills,setSkills,skillInput,setSkillInput,add,remove,location,setLocation,locations,freeOnly,setFreeOnly,resume,setResume,resumeMode,setResumeMode,analyze,loading,error}){return <div className="onboard"><section className="intro"><div className="heroTag">OPPORTUNITY-DRIVEN CAREER PLANNING</div><h2>Don’t just find a job.<br/><em>Find the skill that unlocks it.</em></h2><p>Upload a resume or build a quick profile. SkillPath connects your current skills to curated local jobs, explains the gaps, and builds a measurable training path.</p><div className="heroStats"><div><b>40</b><span>curated jobs</span></div><div><b>60</b><span>training paths</span></div><div><b>RAG</b><span>grounded evidence</span></div></div></section>
 <section className="builder card"><div className="modeSwitch"><button className={!resumeMode?'selected':''} onClick={()=>setResumeMode(false)}>Build profile</button><button className={resumeMode?'selected':''} onClick={()=>setResumeMode(true)}>Upload resume</button></div>{resumeMode?<div className="drop"><input id="resume" type="file" accept="application/pdf" onChange={e=>setResume(e.target.files?.[0]||null)}/><label htmlFor="resume"><span className="uploadIcon">↑</span><b>{resume?resume.name:'Drop your PDF resume here'}</b><small>PDF only · skills are extracted locally</small></label></div>:<><label>Target location</label><select value={location} onChange={e=>setLocation(e.target.value)}>{locations.map(x=><option key={x}>{x}</option>)}</select><label>Your current skills</label><div className="chips">{skills.map(s=><button className="chip" key={s} onClick={()=>remove(s)}>{s}<span>×</span></button>)}</div><div className="addSkill"><input value={skillInput} onChange={e=>setSkillInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Add Java, Docker, AWS…"/><button onClick={add}>+</button></div></>}<label className="check"><input type="checkbox" checked={freeOnly} onChange={e=>setFreeOnly(e.target.checked)}/><span>Prioritize free courses only</span></label><button className="primary" onClick={analyze} disabled={loading||(resumeMode&&!resume)}>{loading?<><span className="spinner"/> Running agents…</>:`Analyze my career ${String.fromCharCode(8594)}`}</button>{error&&<div className="error">{error}</div>}<div className="trust"><span>✓</span> Decisions use deterministic scoring for match, cost and duration.</div></section></div>}

function Results({data,active,setActive,profile,freeOnly}){const top=data.jobs[0];const [sim,setSim]=useState(null);const [simLoading,setSimLoading]=useState(false);const [simError,setSimError]=useState('');const [selectedJob,setSelectedJob]=useState(top);const jobs=active==='jobs'?data.jobs:data.jobs.slice(0,5);const roadmap=data.roadmap;const bestSkill=roadmap.opportunities?.[0];
 const simulate=async(skill)=>{setSimError('');setSimLoading(true);try{if(!selectedJob?.id)throw new Error('Select a job first.');const r=await fetch(API+'/api/simulate-skill',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile,job_id:selectedJob.id,added_skill:skill,free_only:freeOnly})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.detail||'Simulation request failed.');setSim(body)}catch(e){setSimError(e.message||'Simulation failed.')}finally{setSimLoading(false)}};
 return <div className="results">{active==='dashboard'&&<><section className="metricRow"><Metric label="TOP MATCH" value={`${top?.match_score||0}%`} sub={top?.title||'No match'}/><Metric label="LOCAL OPPORTUNITIES" value={data.jobs.length} sub="retrieved + scored"/><Metric label="SKILL GAPS" value={roadmap.missing_skills?.length||0} sub="for target role"/><Metric label="TIME TO READY" value={`${roadmap.weeks||0}w`} sub={`₹${roadmap.cost||0} estimated`}/></section><section className="grid2"><Opportunity job={top} onSelect={setSelectedJob}/><AgentTrace trace={data.trace}/></section><section className="card gapCard"><div className="sectionTitle"><div><div className="eyebrow">OPPORTUNITY-DRIVEN GAPS</div><h3>What should you learn next?</h3></div><span className="sourceBadge">{data.sources.length} grounded sources</span></div><div className="gapGrid">{roadmap.opportunities?.map(o=><div className="gapItem" key={o.skill}><div className="gapTop"><b>{o.skill}</b><span>{o.jobs_unlocked} local jobs</span></div><div className="bar"><i style={{width:`${Math.min(100,o.jobs_unlocked*12)}%`}}/></div><button onClick={()=>simulate(o.skill)}>{simLoading?'Checking…':`What if I learn ${o.skill}?`}</button></div>)}</div>{simError&&<div className="error">{simError}</div>}{sim&&<Simulation sim={sim}/>}</section><Roadmap roadmap={roadmap}/></>}{active==='jobs'&&<JobExplorer jobs={data.jobs} selectedJob={selectedJob} setSelectedJob={setSelectedJob} simulate={simulate} sim={sim} simLoading={simLoading}/>} {active==='roadmap'&&<Roadmap roadmap={roadmap} full/>}<button className="secondary" onClick={()=>window.location.reload()}>← Start another profile</button></div>}

function Metric({label,value,sub}){return <div className="metric card"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Opportunity({job,onSelect}){if(!job)return <div className="card empty"><b>No opportunity found</b><p>Try adding more skills or another location.</p></div>;return <div className="card opportunity"><div className="cardHead"><div><div className="eyebrow">TARGET OPPORTUNITY</div><h3>{job.title}</h3><p>{job.company} · {job.location} · {job.experience}</p></div><div className="scoreRing"><b>{job.match_score}%</b><span>match</span></div></div><div className="salary">₹{(job.salary_min/100000).toFixed(1)}–{(job.salary_max/100000).toFixed(1)}L <span>curated role range</span></div><div className="skillsMatrix">{job.required_skills.map(s=>{const yes=job.matched_skills.includes(s);return <div className={yes?'skill yes':'skill no'} key={s}><span>{yes?'✓':'+'}</span>{s}</div>})}</div><div className="why"><b>Why this match?</b><p>{job.matched_skills.length} of {job.required_skills.length} required skills are already covered. Missing: {job.missing_skills.join(', ')||'none'}.</p></div><button className="linkBtn" onClick={()=>onSelect(job)}>Inspect this opportunity →</button></div>}
function AgentTrace({trace}){return <div className="card traceCard"><div className="eyebrow">AGENT TRACE</div><h3>How SkillPath reasoned</h3>{trace.map((t,i)=><div className="trace" key={i}><span className="traceIcon">✓</span><div><b>{t.agent}</b><small>{t.detail}{t.tool&&<em>tool: {t.tool}</em>}</small></div></div>)}</div>}
function Simulation({sim}){return <div className="simulation"><div><span>WHAT-IF RESULT · {sim.skill} ADDED</span><b>{sim.before.match_score}% → {sim.after.match_score}%</b></div><div><small>Match gain</small><strong>+{sim.match_gain} pts</strong></div><div><small>Local jobs requiring {sim.skill}</small><strong>{sim.local_jobs_with_skill}</strong></div></div>}
function Roadmap({roadmap,full=false}){return <section className={`card roadmap ${full?'full':''}`}><div className="sectionTitle"><div><div className="eyebrow">TIME-TO-READY</div><h3>{roadmap.target_job||'Career roadmap'}</h3><p>Sequential estimate based on the selected course path.</p></div><div className="readyBox"><b>{roadmap.weeks} weeks</b><span>₹{roadmap.cost} total</span></div></div><div className="timeline">{roadmap.steps?.map((c,i)=><div className="step" key={c.id}><div className="stepNum">{String(i+1).padStart(2,'0')}</div><div className="stepInfo"><b>{c.title}</b><span>{c.skill} · {c.provider}</span></div><div className="stepMeta"><b>{c.duration_weeks} wk</b><span>{c.cost===0?'FREE':`₹${c.cost}`}</span></div></div>)}</div><div className="roadmapFooter"><span>Coverage after roadmap: <b>{roadmap.potential_skill_coverage} missing-skill paths</b></span><span>Free-only mode: <b>{roadmap.steps?.every(x=>x.cost===0)?'ON':'OFF'}</b></span></div></section>}
function JobExplorer({jobs,selectedJob,setSelectedJob,simulate,sim,simLoading}){return <section><div className="sectionTitle"><div><div className="eyebrow">CURATED OPPORTUNITIES</div><h3>Jobs you can work toward</h3></div><span className="sourceBadge">{jobs.length} matches</span></div><div className="jobList">{jobs.map(j=><button key={j.id} className={`jobRow ${selectedJob?.id===j.id?'selected':''}`} onClick={()=>setSelectedJob(j)}><div><b>{j.title}</b><span>{j.company} · {j.location}</span></div><div className="jobGaps"><span>{j.missing_skills.length} gaps</span><strong>{j.match_score}%</strong></div></button>)}</div>{selectedJob&&<div className="card detail"><div className="cardHead"><div><div className="eyebrow">JOB EVIDENCE</div><h3>{selectedJob.title}</h3><p>{selectedJob.company} · {selectedJob.location}</p></div><div className="scoreRing"><b>{sim?.job_id===selectedJob.id?sim.after.match_score:selectedJob.match_score}%</b><span>{sim?.job_id===selectedJob.id?'updated':'match'}</span></div></div><p className="description">{selectedJob.description}</p><div className="skillsMatrix">{selectedJob.required_skills.map(s=>{const simulated=sim?.job_id===selectedJob.id&&s.toLowerCase()===sim.skill.toLowerCase();const matched=selectedJob.matched_skills.includes(s)||simulated;return <div className={matched?'skill yes':'skill no'} key={s}><span>{matched?'✓':'+'}</span>{s}</div>})}</div>{selectedJob.missing_skills[0]&&<button className="primary small" onClick={()=>simulate(selectedJob.missing_skills[0])} disabled={simLoading}>{simLoading?'Calculating…':`What if I learn ${selectedJob.missing_skills[0]}?`}</button>}{sim&&sim.job_id===selectedJob.id&&<Simulation sim={sim}/>}</div>}</section>}

createRoot(document.getElementById('root')).render(<App/>);
